### ISSUE TITLE
Error Running the spatial VQA pipeline locally with Docker

### ISSUE THREAD

**Issue by geanrobotics** [remyxai/VQASynth#26]
Hello, I'm getting multiple errors running the docker compose using the suggested dataset as can be seen in the image.

![vqasynth](https://github.com/user-attachments/assets/bc73f055-1547-4f56-a044-d3ae53503695)

I followed these steps whilst also using the suggested dataset in the config file:

1. huggingface-cli login
2. cd /path/to/VQASynth
3. bash run.sh

Any help would be appreciated, thanks in advance!

**Comment by salma-remyx** [comment]
HI @geanrobotics ! Thanks for opening the issue - there was a slight discrepancy in the column name used for the test dataset which has been updated now. You should be able to rerun it again with the same instructions.

Let us know if you run into any issues!
