### ISSUE TITLE
Error/Warning during creating pointcloud

### ISSUE THREAD

**Issue by nasazzam** [remyxai/VQASynth#29]
Hi Remyxai Team,  

Thank you for your excellent work.  
I am receiving warnings while using the Docker image, and the point cloud file is not generating.
![image](https://github.com/user-attachments/assets/3dbbb6cd-5d7a-4ec7-aa1c-3d7b1cf419e3)

In the HF dataset, I am also obtaining measurements that look like this.
![image](https://github.com/user-attachments/assets/f7f311bf-d133-4ac0-b5a6-1b64445827f7)

Could you please explain the filters and how to specify them for my domain task?

Thanks.

**Comment by salma-remyx** [comment]
Hi @Nas-Azzam ! We saw your dataset and reran the pipeline on it with the latest changes which should address the issues. You can see the results [here](https://huggingface.co/datasets/salma-remyx/vqasynth_nas_example_ds?row=0). 

The filters work by using CLIP to extract embeddings from images, tagging each image with its most representative label from those that you provided, and filters images according to their type ([include/exclude](https://github.com/remyxai/VQASynth/blob/main/config/config.yaml#L9)).

You can start with an ideal dataset of about themes/descriptors that would apply to the types of image samples I want to keep. You can also use the tags to design a distribution for your dataset - it may take some iteration to find the best tags for your specific usecase.
