### ISSUE TITLE
inference shell file

### ISSUE THREAD

**Issue by czb2133** [remyxai/VQASynth#4]
It is really surprising that the ckpt is accessible in hugging face. Can you provide a python file for inference?

**Comment by smellslikeml** [comment]
Hey @czb2133 , absolutely! We recommend using the gguf files with llama-cpp-python [abetlen](https://github.com/abetlen)/[llama-cpp-python](https://github.com/abetlen/llama-cpp-python) to load and run inference.
Check out the colab notebook [here](https://colab.research.google.com/drive/1WPE7Br5A5ERSij8BL1M22EoEMLVkD8EP?usp=sharing).

Also, if you want to host your own server, we included a Triton Server deployment using Docker. Check out these [instructions](https://huggingface.co/remyxai/SpaceLLaVA#deployment).
