### ISSUE TITLE
Inquiry about jupyter notebook Spatial Reasoning with Point Clouds

### ISSUE THREAD

**Issue by TikaToka** [remyxai/VQASynth#5]
Hello, thank you for sharing your fantastic work!

I am looking into the jupyter notebookSpatial Reasoning with Point Clouds, and I have a inquiry.

![image](https://github.com/remyxai/VQASynth/assets/49054667/8cb1320b-4a9f-4cf7-b595-ab3bf9c2f41c)
![image](https://github.com/remyxai/VQASynth/assets/49054667/ad25fbad-2da8-4b61-ac3e-814f48935216)

The Heatmap's quality is not good but makes sense, however the sampled coordinates makes no sense.

Do you know why this happens? Is this may be a discrepancy between original image and reshaped image?

---

Furthermore, I saw that depth image provided in jupyter is weird

how can it have only 4 types of value?

![image](https://github.com/remyxai/VQASynth/assets/49054667/82f688f2-4fe2-461f-84ec-5b0eaa214a91)

Thank you in advance

**Comment by TikaToka** [comment]
@remyxai no response?

**Comment by smellslikeml** [comment]
Hi @TikaToka, thanks for your support!
I apologize for the delayed response, updated the settings to receive notifications.

For the scenes we considered, the point sampling strategy works best when objects were rounder and not overlapped.

We're adding a few upgrades to this repo. 
[One change](https://github.com/remyxai/VQASynth/pull/12/files) will prompt SAM2 using Florence-2 for bounding boxes grounding on captions instead of the points sampled from CLIPSeg's attention heatmap.

Unfortunately, it can still fail to separate overlapping objects like your test image

![image](https://github.com/user-attachments/assets/2c931465-7ad5-49fe-92ab-9053422f8525)

**Comment by TikaToka** [comment]
Thanks, I'll look into the updated code :)

**Comment by TikaToka** [comment]
Hello @smellslikeml , Thank you for updating this project!

I have a minor question related to the updates.

You mentioned that using sam2+florence-2 instead of clipseg method,

but as I keep following the codes, there is also a version with using sam2+molmo.

So, the question is that which pipeline is more preferred one?

Thank you in advance!

**Comment by smellslikeml** [comment]
Hey @TikaToka, of course! thank you for your continued support. The performance may vary depending on the data you're working with so it may take an experiment to truly tell. 

One difference to consider between Molmo and Florence is the resources required to run inference - Molmo may require more VRAM and will run slower while Florence is significantly smaller and returns results fairly quickly.

**Comment by TikaToka** [comment]
Hello @smellslikeml, thanks for your quick assistance!

I'm reviewing the molmo code in detail but am having trouble reproducing its response.

In the [pull request](https://github.com/remyxai/VQASynth/issues/27), you attached an image where the points are correctly aligned with the object names. However, when I run the code from [this PR](https://github.com/remyxai/VQASynth/pull/35/files) using the prompt "Point to the object of interest in the scene," the objects are detected correctly, but all labels appear as "object of interest in the scene" instead of their specific names.

![Image](https://github.com/user-attachments/assets/1af4ba2e-0055-4995-b91d-ca7b03247aa1)

Did I miss something in the implementation? 

Thank you in advance!
