### ISSUE TITLE
getting tis error very often:

### ISSUE THREAD

**Issue by monjha** [remyxai/VQASynth#7]

**Comment by monjha** [comment]
Getting this error very often:
 llava_eval_image_embed : failed to eval
caption_processor-1     | Llama.generate: prefix-match hit

Tried to run for more than 24 hours and still the label file wasn't generated,

**Comment by salma-remyx** [comment]
Hey @monjha ! Thanks for bringing this to our attention - we've recently updated the full pipeline to use more lightweight models which should help address the issue above. 
The previous version of the pipeline relied on a larger model for captioning which caused it to be very slow
