### ISSUE TITLE
Inference code for SpaceMantis

### ISSUE THREAD

**Issue by dohyun1411** [remyxai/VQASynth#8]
I found the inference code for SpaceLLaVA with llama-cpp-python [here](https://colab.research.google.com/drive/1WPE7Br5A5ERSij8BL1M22EoEMLVkD8EP?usp=sharing).
Is there any inference code for SpaceMantis like this one?

**Comment by salma-remyx** [comment]
Hey @dohyun1411, thank you for interest! You can try the inference code in the [SpaceMantis model card](https://huggingface.co/remyxai/SpaceMantis#quick-start)
